export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const LIKE = 'LIKE';


export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const GET_LIST_BUY_REQUEST = 'GET_LIST_BUY_REQUEST';
export const GET_LIST_BUY_SUCCESS = 'GET_LIST_BUY_SUCCESS';
export const GET_LIST_BUY_FAIL = 'GET_LIST_BUY_FAIL';

export const OPTION_BUY_REQUEST = 'OPTION_BUY_REQUEST';
export const OPTION_BUY_SUCCESS = 'OPTION_BUY_SUCCESS';
export const OPTION_BUY_FAIL = 'OPTION_BUY_FAIL';

export const OPTION_BUY_DETAIL_REQUEST = 'OPTION_BUY_DETAIL_REQUEST';
export const OPTION_BUY_DETAIL_SUCCESS = 'OPTION_BUY_DETAIL_SUCCESS';
export const OPTION_BUY_DETAIL_FAIL = 'OPTION_BUY_DETAIL_FAIL';
